# DEV Workflow
workflows:
  android-workflow:           # workflow ID
    name: Android Workflow    # workflow name displayed in UI
    instance_type: mac_mini_m1   # machine type to use (currently supported: mac_mini_m1 `mac_mini`, `mac_pro`, `linux`, `linux_x2`)
    max_build_duration: 30    # build duration in minutes (min 1, max 120)
    environment:
      groups:             # Define your environment variables here
        - DEV_VARIABLES
      node: 18.10.0     # Define default, latest, current, lts, carbon (or another stream), nightly or version
      npm: 8.11.0       # Define default, latest, next, lts or version
      ndk: default         # Define default or revision (e.g., r19c)         # Gradle cache
    scripts:      
      - name: Install npm dependencies for Ionic project
        script: |
          npm install --force
      - name: check software versions
        script: |
          ionic --version
          npx cap --version  
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH                    
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Set up key.properties
        script: | 
          cat >> "$CM_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF
      - name: Update dependencies and copy web assets to native project
        script: |
          npx cap copy
      - name: Build Android release
        script: |  
          cd android         
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - himesh@nevercode.io
        notify:
          success: true
          failure: true